---
name: Validate local database

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: true

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: |
                      requirements*.txt

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Lint repository
              run: pre-commit run --all-files

    validate:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: true

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: |
                      requirements*.txt

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run database ingestion tasks
              run: |
                  invoke regenerate-models
